version: '3.9'

services:
  pyleton:
    container_name: pyleton
    build:
      context: ../
      dockerfile: docker/dev/Dockerfile
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
    environment:
      - RABBITMQ_HIST=rabbitmq:5672


  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    ports:
        - 5672:5672
        - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass
